on load:
    set {quests::firstSlay::objective} to "Learn the fundamentals and demonstrate your worthiness."
    set {quests::animalFood::objective} to "Assist Eirik in gathering wheat to feed the animals."
    set {quests::rootedChallenge::objective} to "Help Uno to defeat the Groot in his search for the Rooted Skin."
    set {quests::mysteryItem::objective} to "Find the mystery item Bjarne is looking for."
