on load:
    set {quests::firstSlay::quota::*} to ("Kill 10 animals in and around Arland.") 
    set {quests::animalFood::quota::*} to ("Harvest 192x Wheat and bring it to Eirik.") 
    set {quests::rootedChallenge::quota::*} to ("Defeat the Groot and give Uno 1x Rooted Skin.") 
    set {quests::mysteryItem::quota::*} to ("Give Bjarne the mystery item is he looking for.") 
    set {quests::luckyCarrot::quota::*} to ("Deliver a year's worth of carrots to Dalur.", "Assist Dalur in finding the golden carrot.") 
    set {quests::conjecture::quota::*} to ("Give Oliver 1x Enormous Shroom.", "Supply Oliver with 2x Rooted Skin.") 
    set {quests::healthyCure::quota::*} to ("Get one red apple and one brownie for Mari.") 
