on load:

# Reforge

    set {_icicleStone} to player skull with nbt "{display:{Name:""Gem (blue)""},SkullOwner:{Id:""e96057b4-3778-4d48-ac73-ce7871fa67b7"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTNlZGVlZWM2ZDczYTRiZTZlYTY4NmNjN2IxNDk1ZGU2OGU4NGMwMjQwNDRlOGQzZTIwNDFjZTQ3YTY5M2M5NSJ9fX0=""}]}}}" named "&5Icicle Stone" with lore "&7Reforge Stone.", "", "&7Can be given to the Reforger", "&7to apply the &3Ravishing&7 reforge", "&7on a pickaxe.", "", "&7Ore: &3+2", "", "&5★★&8☆☆☆" and "&5&lEPIC"
    set {_charmingStone} to player skull with nbt "{display:{Name:""Malachite Gem""},SkullOwner:{Id:""30654419-78c7-4808-9568-26271e6ab95f"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmU2Y2EzY2U1ZDg5YWNiMDZhNjQzZjQ5ZjUyNzQ4NTVlZGVlNmVlYjFhNTQ1MTViMzA0MGExYjNmOGNiYjdhMSJ9fX0=""}]}}}" named "&5Charming Stone" with lore "&7Reforge Stone.", "", "&7Can be given to the Reforger", "&7to apply the &bCharming&7 reforge", "&7on a hoe.", "", "&7Crops: &b+3", "", "&5★&8☆☆☆☆" and "&5&lEPIC"


# charming
    set {items::reforgeItems::*} to ({_icicleStone}, {_charmingStone})